config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :integer          not null, primary key
#  band_id        :integer          not null
#  title          :string           not null
#  live_or_studio :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Album < ActiveRecord::Base
  validates :band_id, :title, presence: true

  belongs_to :band

  has_many :tracks


end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums

  has_many :tracks, through: :albums, source: :tracks
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id               :integer          not null, primary key
#  album_id         :integer          not null
#  song_title       :string           not null
#  bonus_or_regular :string
#  lyrics           :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Track < ActiveRecord::Base
  validates :album_id, :song_title, presence: true

  belongs_to :album

  has_one :band, through: :album, source: :band
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true

  after_initialize :ensure_session_token


  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
    @band_id = params[:band_id].to_i
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save!
      redirect_to band_url(@album.band_id)
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
  
    render :show
  end

  private

  def album_params
    params.require(:album).permit(:title, :band_id, :live_or_studio)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  helper_method :logged_in?, :current_user


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
  end

  def index
  end

  def destroy
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
              params[:user][:email],
              params[:user][:password])

    unless @user.nil?
      login_user!(@user)
      redirect_to user_url(@user)
    else
      #put some errors like username or password not recognized
      render :new
    end

  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @track = Track.new
    @album_id = params[:album_id].to_i
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      #need to make show page
      redirect_to album_url(@track.album_id)
    else
      render :new
    end
  end


  private

  def track_params
    params.require(:track).permit(:song_title, :bonus_or_regular, :album_id, :lyrics)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save!
      login_user!(@user)
      # session[session_token] = User.session_token
      render users_url(user)
    else
      # flash.now[:errors] = @user.errors.f
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end


end




# in cats controller
    # @cat = Cat.new(cat_params)
    # @cat.owner_id = current_user.id

app/helpers/albums_helper.rb
module AlbumsHelper

  # def selected
  #   "selected" if @album.band_id == params[]
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # def auth_token
  #   "<input type='hidden' name='authenticity_token' value=''<%= form_authenticity_token %>''>".html_safe
  # end
  #


end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<h1>List An Album</h1>

<form action="<%=albums_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


  <label for="band_name">Band Name</label>
  <select name="album[band_id]" id="band_name">
    <% Band.all.each do |band| %>
      <option
        value="<%=band.id%>"
        <%= "selected" if band.id == @band_id %>
        ><%=band.name%></option>
      <% end %>
  </select>

  <br><br>

  <label for="album_name">Album Name</label>
  <input type="text" name="album[title]" value="<%= @album.title %>" id="album_name">

  <br><br>

  <!-- radio buttons for live or studio -->
  <label for="live_or_studio">Live or Studio Album</label>
  <br>
    <input type="radio" name="album[live_or_studio]" value= "live" id="live_or_studio">Live</input>
  <br>
    <input type="radio" name="album[live_or_studio]" value= "studio" id="live_or_studio">Studio</input>

  <br><br>
  <input type="submit" value="Create Album">
  <br><br>
</form>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>


<h2>Artist:</h2>
  <%= link_to @album.band.name, band_url(@album.band) %>

<h2>Type of Album</h2>

  <%= @album.live_or_studio.capitalize %>
  <br>

<h2>Tracks</h2>
  <ul>
    <% @album.tracks.each do |track| %>
      <li><%=track.song_title %></li>
    <% end %>
  </ul>

app/views/bands/new.html.erb
<h1>Create a band</h1>

<form action="/bands" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="band_name">Band Name</label>
  <input type="text" name="band[name]" value="<%= @band.name %>">

  <input type="submit" value="Create band">

</form>

app/views/bands/show.html.erb
<h1><%= @band.name %> </h1>

<h2>Albums</h2>
  <ul>
    <% @band.albums.each do |album| %>
      <li><%=link_to album.title, album_url(album) %></li>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% if logged_in?  %>
  <%= button_to "Log out", session_url, method: :delete %>
<% end %>
</body>
</html>

app/views/tracks/new.html.erb
<h1>Make a track</h1>

<form action="<%= tracks_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  
  <label for="song_name">Song Name</label>
  <input type="text"
      name="track[song_title]"
      value="<%= @track.song_title %>"
      id="song_name">

  <br><br>

  <!--  maybe we don't put the album as a selection they have to add it to the al-->
  <label for="album">Album</label>
  <select name="track[album_id]">
    <% Album.all.each do |album| %>
      <option
        value="<%=album.id%>"
        <%= "selected" if album.id == @album_id %>
        ><%=album.title%></option>
      <% end %>
  </select>

  <br><br>

  <label for="type_of_track">Bonus or Regular Track</label>
  <br>
  <input
    type="radio"
    name="track[bonus_or_regular]"
    value="bonus"
    <%="checked" if @track.bonus_or_regular == "bonus"%>>Bonus</input>

  <input
    type="radio"
    name="track[bonus_or_regular]"
    value="regular"
    <%="checked" if @track.bonus_or_regular == "regular"%>>Regular</input>

  <br><br>
  <label for="song_lyrics">Lyrics</label>
  <input type="textarea" name="track[lyrics]" value="<%= @track.lyrics %>" id="song_lyrics">

  <br><br>
  <input type="submit"  value="Write that track">
  <br><br>
</form>

app/views/users/new.html.erb
<h1>Sign up</h1>

<form action="/users" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="user_email">Email</label>
  <input type="text" name="user[email]" value="<%= @user.email %>" id="user_email">
  <br>

  <label for="user_password">Password</label>
  <input type="password" name="user[password]">
  <br>

  <input type="submit" name="name" value="Sign up">

</form>

app/views/users/show.html.erb
<h1><%= @user.email %> </h1>